PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!$"

PalletTown_PlayersHouse_2F_Text_Random_Encounters::
  .string "Wild Pokemon are random?$"

PalletTown_PlayersHouse_2F_Text_Random_Trainers::
  .string "Trainers Pokemon are random?$"

PalletTown_PlayersHouse_2F_Text_Random_Starter::
  .string "Starter Pokemon are random?$"

PalletTown_PlayersHouse_2F_Text_Random_Gift_Pokemon::
  .string "Other gifted Pokemon are random?$"

PalletTown_PlayersHouse_2F_Text_Random_Evolution::
  .string "Evolutions are random?$"

PalletTown_PlayersHouse_2F_Text_Random_Move::
  .string "Pokemon moves are random?$"

PalletTown_PlayersHouse_2F_Text_Random_Item::
  .string "Hidden items are random?$"

  PalletTown_PlayersHouse_2F_Text_Random_Ability::
    .string "Pokemon abilities are random?$"

